---
ike:
  profile-name: IKE-NSX-T
  gateway: IKE-GW-NSX-T-REGION-1-AZ-1
  localif: loopback.128
  localaddr: 1.1.1.1
  localid: 1.1.1.1
  localidtype: ipaddr
  peeraddr: 1.0.0.1
  peerid: 1.0.0.1
  peeridtype: ipaddr
ipsec:
  profile-name: CRYPTO-NSX-T
  tunnelname: IPSEC-NSX-T-REGION-1-AZ-1-T0-1
  tunnelid: 128
  tunnelip: 169.254.249.1/30
ipv4: 
  localaddr: 1.1.1.1
  peeraddr: 1.0.0.1
bgp:
  peergroup: NSX-T-REGION-1-AZ-1
  peer: NSX-T-REGION-1-AZ-1-T0-1
  peerip: 169.254.249.2
  localasn: 65000
  peeroneasn: 64980
  importfilter: NSX-T-REGION-1-AZ-1-IMPORT
  importprefix: 10.0.0.0/8
  exportfilter: NSX-T-REGION-1-AZ-1-EXPORT
  exportprefix: 10.0.0.0/8
  redistprofileout: NSX-T-REGION-1-AZ-1-REDIST-OUT
